services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  Ivoz\Core\Application\Service\Assembler\DtoAssembler:
    arguments:
      $serviceContainer: '@service_container'

  Ivoz\Core\Application\Service\Assembler\EntityAssembler:
    arguments:
      $serviceContainer: '@service_container'
