services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ivoz\Core\Infrastructure\Application\DoctrineForeignKeyTransformer:
    arguments:
    - '@doctrine.orm.entity_manager'

  Ivoz\Core\Application\ForeignKeyTransformerInterface:
    '@Ivoz\Core\Infrastructure\Application\DoctrineForeignKeyTransformer'

  Ivoz\Core\Infrastructure\Application\DoctrineCollectionTransformer:
    arguments:
    - '@doctrine.orm.entity_manager'

  Ivoz\Core\Domain\Model\EntityInterface\CollectionTransformerInterface:
    '@Ivoz\Core\Infrastructure\Application\DoctrineCollectionTransformer'

  Ivoz\Core\Application\Service\CreateEntityFromDTO: ~

  Ivoz\Core\Application\Service\UpdateEntityFromDTO:
    public: true

  Ivoz\Core\Domain\Service\EntityPersisterInterface:
    '@Ivoz\Core\Infrastructure\Domain\Service\DoctrineEntityPersister'

  Ivoz\Core\Application\Service\EntityTools:
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'
    public: true
    lazy: true
