services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ivoz\Core\Infrastructure\Domain\Service\Cgrates\CompanyBalanceService: ~

  Ivoz\Core\Infrastructure\Domain\Service\Cgrates\CarrierBalanceService: ~

  Ivoz\Core\Infrastructure\Domain\Service\Cgrates\BillingService:
    public: true

  Ivoz\Core\Infrastructure\Domain\Service\Cgrates\SetMaxUsageThresholdService:
    public: true

  Ivoz\Core\Infrastructure\Domain\Service\Cgrates\ReassembleTriggerService:
    public: true

  Ivoz\Core\Infrastructure\Domain\Service\Cgrates\EnableAccountService:
    public: true

  Ivoz\Core\Infrastructure\Domain\Service\Cgrates\ReloadService:
    public: true

  Ivoz\Core\Infrastructure\Domain\Service\Cgrates\LoadTpAccountAction:  ~

  Ivoz\Core\Infrastructure\Domain\Service\Cgrates\RemoveTpAccountAction:  ~

  Ivoz\Core\Infrastructure\Domain\Service\Cgrates\LoadTpRatingProfile:  ~

  Ivoz\Core\Infrastructure\Domain\Service\Cgrates\RemoveTpRatingProfile:  ~

  Ivoz\Core\Infrastructure\Domain\Service\Cgrates\RerateCallService:
    public: true

  Ivoz\Core\Infrastructure\Domain\Service\Cgrates\FetchCallStatsService: ~

  Ivoz\Core\Infrastructure\Domain\Service\Cgrates\ProcessExternalCdr: ~
