services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Ivoz\Core\Infrastructure\Domain\Service\Cgrates\FakeCgrRpcClient: ~

  Ivoz\Core\Infrastructure\Domain\Service\Cgrates\CgrRpcClient:
    factory: ['Ivoz\Core\Infrastructure\Domain\Service\Cgrates\CgrRpcClient', 'factory']
    arguments: ['trunks.ivozprovider.local:2080/jsonrpc']
    tags:
    - { name: test_double, fake: 'Ivoz\Core\Infrastructure\Domain\Service\Cgrates\FakeCgrRpcClient' }

  Graze\GuzzleHttp\JsonRpc\ClientInterface:
    alias: 'Ivoz\Core\Infrastructure\Domain\Service\Cgrates\CgrRpcClient'
