services:
  _defaults:
    autowire: true
    public: false

  Ivoz\Core\Infrastructure\Domain\Service\Gearman\Client\FakeXmlRpcTrunksRequest: ~
  Ivoz\Core\Infrastructure\Domain\Service\Gearman\Client\FakeXmlRpcUsersRequest: ~
